### affiche challenge
get http://localhost:8080/api/challenges



#####
post http://localhost:8080/api/signup

####

post http://localhost:8080/api/login

####

get http://localhost:8080/api/challenges/2